package main

const STARTING_FEN string = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"

const BOARD_SQUARES int = 120
const BOARD_WIDTH_HEIGHT int = 8

const VERTICAL_MOVE_DIST int = 10
const HORIZONTAL_MOVE_DIST int = 1

const UP int = -1
const LEFT int = -1
const DOWN int = 1
const RIGHT int = 1

const MAX_GENERATED_MOVES int = 512
const MAX_PAWN_MOVES int = 12
const MAX_KNIGHT_MOVES int = 8
const MAX_BISHOP_MOVES int = 13
const MAX_ROOK_MOVES int = 14
const MAX_QUEEN_MOVES int = 27
const MAX_KING_MOVES int = 8

const (
	INVALID Square = iota
	WHITE_PAWN
	WHITE_KNIGHT
	WHITE_BISHOP
	WHITE_ROOK
	WHITE_QUEEN
	WHITE_KING
	BLACK_PAWN
	BLACK_KNIGHT
	BLACK_BISHOP
	BLACK_ROOK
	BLACK_QUEEN
	BLACK_KING
	EMPTY
)

const (
	WHITE Color = iota
	BLACK
	COLOR_NONE
)

const (
	FILE_A File = iota
	FILE_B
	FILE_C
	FILE_D
	FILE_E
	FILE_F
	FILE_G
	FILE_H
	FILE_NONE
)

const (
	RANK_EIGHT Rank = iota
	RANK_SEVEN
	RANK_SIX
	RANK_FIVE
	RANK_FOUR
	RANK_THREE
	RANK_TWO
	RANK_ONE
	RANK_NONE
)

const (
	QUIET MoveKind = iota
	DOUBLE_PAWN_PUSH
	KING_CASTLE
	QUEEN_CASTLE
	CAPTURE
	EP_CAPTURE
	KNIGHT_PROMOTION
	BISHOP_PROMOTION
	ROOK_PROMOTION
	QUEEN_PROMOTION
	KNIGHT_PROMOTION_CAPTURE
	BISHOP_PROMOTION_CAPTURE
	ROOK_PROMOTION_CAPTURE
	QUEEN_PROMOTION_CAPTURE
)
