name: CI
on:
  - pull_request
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Run Tests
        run: |
          go mod download
          go test -v -count=1 -short ./src/...
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.44.2
          args: --fast
